// apps/admin/src/pages/login/index.vue
<template>
  <main
    class="relative min-h-screen overflow-hidden bg-[linear-gradient(135deg,color-mix(in_srgb,var(--color-primary)_16%,transparent),transparent_42%),linear-gradient(225deg,color-mix(in_srgb,var(--color-warning)_10%,transparent),transparent_38%),var(--color-background)] text-tcolor before:pointer-events-none before:absolute before:inset-0 before:bg-[linear-gradient(color-mix(in_srgb,var(--color-primary)_10%,transparent)_1px,transparent_1px),linear-gradient(90deg,color-mix(in_srgb,var(--color-primary)_10%,transparent)_1px,transparent_1px)] before:bg-[length:44px_44px] before:content-[''] before:[mask-image:linear-gradient(to_bottom,black,transparent_72%)]"
  >
    <section
      class="relative mx-auto grid min-h-screen w-full max-w-6xl items-center gap-8 px-5 py-8 lg:grid-cols-[minmax(0,1fr)_420px]"
    >
      <div class="hidden lg:block">
        <div
          class="inline-flex h-10 items-center gap-2 rounded-lg border border-primary-white bg-white/80 px-3 text-sm font-semibold text-primary shadow-sm"
        >
          <LucideShieldCheck class="size-4" aria-hidden="true" />
          Admin Console
        </div>
        <h1 class="mt-6 max-w-xl text-4xl leading-tight font-bold text-tcolor-dark">
          统一管理用户、任务与权限
        </h1>
        <p class="mt-4 max-w-lg text-base leading-7 text-tcolor-light">
          使用同一套主题色驱动管理台界面，登录后进入系统工作区。
        </p>
        <div class="mt-8 grid max-w-xl grid-cols-3 gap-3">
          <div class="rounded-lg border border-white/80 bg-white/75 p-4 shadow-sm">
            <div class="text-lg font-bold text-primary">User</div>
            <div class="mt-1 text-xs text-tcolor-light">用户管理</div>
          </div>
          <div class="rounded-lg border border-white/80 bg-white/75 p-4 shadow-sm">
            <div class="text-lg font-bold text-success">Ready</div>
            <div class="mt-1 text-xs text-tcolor-light">任务调度</div>
          </div>
          <div class="rounded-lg border border-white/80 bg-white/75 p-4 shadow-sm">
            <div class="text-lg font-bold text-warning">Guard</div>
            <div class="mt-1 text-xs text-tcolor-light">权限控制</div>
          </div>
        </div>
      </div>

      <div
        class="mx-auto w-full max-w-[420px] rounded-lg border border-white/80 bg-white/95 p-7 shadow-[0_24px_80px_rgb(15_23_42_/_16%)] backdrop-blur"
      >
        <div class="mb-7 flex items-start justify-between gap-4">
          <div>
            <p class="text-sm font-semibold text-primary">欢迎回来</p>
            <h2 class="mt-2 text-2xl font-bold text-tcolor-dark">登录管理台</h2>
            <p class="mt-1 text-sm text-tcolor-light">Management workspace</p>
          </div>
          <div
            class="inline-flex size-11 shrink-0 items-center justify-center rounded-lg bg-primary-white text-primary shadow-[inset_0_0_0_1px_color-mix(in_srgb,var(--color-primary)_16%,transparent)]"
          >
            <LucideLogIn class="size-5" aria-hidden="true" />
          </div>
        </div>

        <div
          class="space-y-4 [&_.el-input__inner]:text-tcolor-dark [&_.el-input__inner::placeholder]:text-tcolor-light [&_.el-input__prefix]:text-tcolor-light [&_.el-input__wrapper]:min-h-[46px] [&_.el-input__wrapper]:rounded-lg [&_.el-input__wrapper]:border [&_.el-input__wrapper]:border-tcolor-white [&_.el-input__wrapper]:bg-white/90 [&_.el-input__wrapper]:shadow-none [&_.el-input__wrapper]:transition [&_.el-input__wrapper.is-focus]:border-primary [&_.el-input__wrapper.is-focus]:shadow-[0_0_0_3px_var(--color-primary-soft)]"
        >
          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-tcolor">用户名</span>
            <el-input
              v-model="sysForm.username"
              size="large"
              autocomplete="username"
              :prefix-icon="LucideUserRound"
              placeholder="请输入用户名"
            ></el-input>
          </label>

          <label class="block">
            <span class="mb-1.5 block text-sm font-medium text-tcolor">密码</span>
            <el-input
              v-model="sysForm.password"
              size="large"
              type="password"
              autocomplete="current-password"
              show-password
              :prefix-icon="LucideLockKeyhole"
              :validate-event="false"
              placeholder="请输入密码"
              @keyup.enter="sysSubmit()"
            ></el-input>
          </label>

          <el-button
            class="w-full !h-[46px] !rounded-lg !font-bold !shadow-[0_14px_28px_color-mix(in_srgb,var(--color-primary)_24%,transparent)]"
            type="primary"
            size="large"
            :loading="submitting"
            :disabled="submitting || !sysForm.username.trim() || !sysForm.password"
            @click="sysSubmit()"
          >
            登录
          </el-button>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
import { api } from '@/utils';
import { ref } from 'vue';
import LucideLockKeyhole from '~icons/lucide/lock-keyhole';
import LucideLogIn from '~icons/lucide/log-in';
import LucideShieldCheck from '~icons/lucide/shield-check';
import LucideUserRound from '~icons/lucide/user-round';

import { ElButton, ElInput } from 'element-plus';
import { loginHandleRedirect } from './login';

const sysForm = ref({
  username: '',
  password: '',
});
const submitting = ref(false);

/**
 * 校验登录表单并提交认证请求，成功后按 redirect 参数跳转。
 */
async function sysSubmit() {
  if (submitting.value) {
    return;
  }

  let { username, password } = sysForm.value;
  username = username.trim();
  if (!username || !password) {
    return;
  }

  submitting.value = true;

  try {
    const info = await api('/login/login', {
      username,
      password,
    });

    loginHandleRedirect(
      info,
      new URLSearchParams(location.search).get('redirect'),
    );
  } finally {
    submitting.value = false;
  }
}
</script>

// apps/client/src/pages/login/index.tsx
import { useMutation } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import LucideArrowLeft from '~icons/lucide/arrow-left';
import LucideLockKeyhole from '~icons/lucide/lock-keyhole';
import LucideLogIn from '~icons/lucide/log-in';
import LucideShieldCheck from '~icons/lucide/shield-check';
import LucideUserRound from '~icons/lucide/user-round';

import { api } from '@/utils/api';
import { useSessionModel } from '@/model/session';

/**
 * 渲染客户端登录页。
 *
 * @returns 登录表单页面节点。
 */
export function LoginPage() {
  const navigate = useNavigate();
  const setSession = useSessionModel((state) => state.setSession);
  const [form, setForm] = useState({
    username: '',
    password: '',
  });

  const loginMutation = useMutation({
    mutationFn: (body: typeof form) => api('/login/login', body),
    onSuccess(response) {
      setSession(response);
      void navigate({ to: '/' });
    },
  });

  return (
    <section className="grid w-full items-center gap-8 lg:grid-cols-[minmax(0,1fr)_420px]">
      <div className="hidden lg:block">
        <div className="inline-flex h-10 items-center gap-2 rounded border border-primary-soft bg-primary-soft px-3 text-sm font-medium text-primary-2">
          <LucideShieldCheck className="size-4" aria-hidden />
          Client Workspace
        </div>
        <h1 className="mt-6 max-w-xl text-4xl font-semibold text-app-text">
          Workspace control, ready when you are.
        </h1>
        <p className="mt-4 max-w-lg text-base leading-7 text-app-muted">
          Secure access for runtime checks, user sessions, and workspace preferences.
        </p>
        <div className="mt-8 grid max-w-xl grid-cols-3 gap-3">
          <div className="rounded border border-app-border bg-app-surface p-4">
            <div className="text-lg font-semibold text-app-text">SPA</div>
            <div className="mt-1 text-xs text-app-muted">Mode</div>
          </div>
          <div className="rounded border border-app-border bg-app-surface p-4">
            <div className="text-lg font-semibold text-success-3">Ready</div>
            <div className="mt-1 text-xs text-app-muted">Status</div>
          </div>
          <div className="rounded border border-app-border bg-app-surface p-4">
            <div className="text-lg font-semibold text-warning-3">Live</div>
            <div className="mt-1 text-xs text-app-muted">API</div>
          </div>
        </div>
      </div>

      <div className="mx-auto w-full max-w-[420px] rounded-lg border border-app-border bg-app-surface p-6 shadow-[0_24px_80px_rgba(0,0,0,0.35)] sm:p-7">
        <div className="mb-7 flex items-start justify-between gap-4">
          <div>
            <p className="text-sm font-medium text-primary-3">Welcome back</p>
            <h1 className="mt-2 text-2xl font-semibold text-app-text">Sign In</h1>
            <p className="mt-1 text-sm text-app-muted">Access the client workspace</p>
          </div>
          <div className="inline-flex size-11 shrink-0 items-center justify-center rounded bg-primary-soft text-primary-2">
            <LucideLogIn className="size-5" aria-hidden />
          </div>
        </div>

        <form
          className="space-y-4"
          onSubmit={(event) => {
            event.preventDefault();
            loginMutation.mutate(form);
          }}
        >
          <label className="block">
            <span className="mb-1.5 block text-sm text-app-muted">Username</span>
            <div className="relative">
              <LucideUserRound
                className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-app-subtle"
                aria-hidden
              />
              <input
                className="h-11 w-full rounded border border-app-border-strong bg-app-bg px-9 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-primary focus:ring-2 focus:ring-primary-soft"
                value={form.username}
                autoComplete="username"
                placeholder="Username"
                onChange={(event) =>
                  setForm((value) => ({
                    ...value,
                    username: event.target.value,
                  }))
                }
              />
            </div>
          </label>
          <label className="block">
            <span className="mb-1.5 block text-sm text-app-muted">Password</span>
            <div className="relative">
              <LucideLockKeyhole
                className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-app-subtle"
                aria-hidden
              />
              <input
                className="h-11 w-full rounded border border-app-border-strong bg-app-bg px-9 text-sm text-app-text outline-none transition placeholder:text-app-subtle focus:border-primary focus:ring-2 focus:ring-primary-soft"
                value={form.password}
                type="password"
                autoComplete="current-password"
                placeholder="Password"
                onChange={(event) =>
                  setForm((value) => ({
                    ...value,
                    password: event.target.value,
                  }))
                }
              />
            </div>
          </label>

          {loginMutation.error && (
            <div className="rounded border border-error-soft bg-error-soft px-3 py-2 text-sm text-error-3">
              {loginMutation.error.message}
            </div>
          )}

          <button
            type="submit"
            className="inline-flex h-11 w-full items-center justify-center gap-2 rounded bg-primary px-3 text-sm font-semibold text-app-inverse transition hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-60"
            disabled={loginMutation.isPending}
          >
            <LucideLogIn className="size-4" aria-hidden />
            {loginMutation.isPending ? 'Signing in...' : 'Sign in'}
          </button>
        </form>

        <Link
          to="/"
          className="mt-5 inline-flex items-center gap-2 text-sm text-primary-3 hover:text-primary-2"
        >
          <LucideArrowLeft className="size-4" aria-hidden />
          Back to dashboard
        </Link>
      </div>
    </section>
  );
}
